### ISSUE TITLE
Временни файлове НЕ трабва да са във git

### ISSUE THREAD

**Issue by vvalchev** [nikolatzotchev/PackageTrack#5]
Това са:

IntelliJ IDEA проект:
`Server/.idea/**`
`Server/Server.iml`

Компилиране от Maven класове:
`Server/target/**`

Това са генерирани артефакти, които винаги ще се модифицират, при компилиране на проекта. Затова е добре да бъдат премахнати, за да не бъдат commit-вани постоянно - така е много трудно да разбереш какво точно е променено, защото commit-a става огромен.

За да не се добавят по погрешка такива файлове обикновено в root-a на проекта се създава един `.gitignore` файл. Ето и как би трябвало да изглежда той:

```
### Maven ###
target/

### MacOs ###
.DS_Store

### STS ###
.apt_generated
.classpath
.factorypath
.project
.settings
.springBeans

### IntelliJ IDEA ###
.idea
*.iws
*.iml
*.ipr

### NetBeans ###
nbproject/private/
build/
nbbuild/
dist/
nbdist/
.nb-gradle/
```

**Comment by nikolatzotchev** [comment]
132e10f536de453c123222d20a02f0b57c8e78ce

**Comment by vvalchev** [comment]
Ако в commit message напишеш # последван от номера на issue. Github автоматично щe добави линк към комит-а, като коментар в issue-то.

**Comment by vvalchev** [comment]
файловете отново са добавени в гит (виж Server/target & Server/.idea)

**Comment by vvalchev** [comment]
мисля че .gitignore трябва да е във рут-а на проекта, а не във всяка под-директория

**Comment by nikolatzotchev** [comment]
Аз вчера прочетох и пишеше, че не е проблем, защото нали може да искаш да игнорираш едни файлове от едно място, които обаче са важни за друго.
