### ISSUE TITLE
Създаване на нов endpoint /api/devices/{deviceId}/report

### ISSUE THREAD

**Issue by vvalchev** [nikolatzotchev/PackageTrack#6]
В момента има /api/trips/{tripId}/reports на който у-вата подават своите данни.

Това означава, че те трябва да знаят не само своето deviceId, но и текущият си tripId, което съответно е предпоставка за грешки.

Би трябвало deviceId да е достатъчно. В такъв случай у-вата би трябвало да пратя POST заявка към /api/devices/{deviceId}/report.

Вътрешно този метод трябва да вземе посленият trip.
Ако той не съществува или вече е приключен (зададен е endTime) се генерира грешка.

Ако trip-a още не е започнал, (т.е. няма startTime) данните се игнорират.

Ако такъв трип съществува, и е стартиран, тогава и само тогава данните се записват в базата от данни.

**Comment by nikolatzotchev** [comment]
5ee07f82afa27595002d613e6c1d5f7295ac9f27

**Comment by nikolatzotchev** [comment]
e6bec699caedeeeb777ff94a60ed8cf3e1fc6597

**Comment by vvalchev** [comment]
Добре е винаги да спазваш принципа един проблем, един комит. Избягвай с един комит да оправяш няколко issues.

Причината е проста:
ако работиш по професионален проект, след време може да се окаже, че някъде има бъг. Често се случва този проблем преди да е бил уж оправен. Ако "фикс"-а е в даден комит, можеш много лесно да видиш как точно е оправен проблема и дали това е истинско решение.
Но ако комит-а включва множество промени, ще отнеме доста повече време да се прецени коя промяна точно е важната.

**Comment by nikolatzotchev** [comment]
Добре ще го имам предвит, но аз просто забравям някои неща и ги добавям в следващ комит а отностно затварянето на issue така ли се прави, коментирам комита и го затварям.

**Comment by nikolatzotchev** [comment]
Извинявай ти си ми го казал в следващото issue. Мерси

**Comment by vvalchev** [comment]
https://help.github.com/articles/closing-issues-using-keywords/
