### ISSUE TITLE
Използване на унифициран StyleGuide

### ISSUE THREAD

**Issue by vvalchev** [nikolatzotchev/PackageTrack#9]
В случаят е добре да ползваме Google Style Guide, поради простата причина, че той е приложим не само за Java но и за другите езици, които ще се наложи да ползваме.

Конфигурация за Eclipse & Idea може да се дръпнат от тук:
https://github.com/google/styleguide

Форматирането на кода е много често приемано за тривиално, но всъщност е от изключителна важност, когато работиш върху професионални проекти, защото:
* улеснява четаемостта на кода
* всички колеги използват един стил, така че се чустват комфортно и с чужд код (и съответно работят по-бързо и ефективно)
* улеснява се поддръжката на проекта, защото дори и след година, когато погледнеш отново, всичко ще е чисто и подредено (и поправките ще са по бързи)

Същността на това изискване е:
1. да се инсталира google style в eclipse/idea
2. да се преформатира целият наличен код в този стил, използвайките IDE-то

**Comment by nikolatzotchev** [comment]
762f04544775bf37db64ece429df059aa9d45d57
